apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: reversewordsapps.linuxera.org
spec:
  group: linuxera.org
  names:
    kind: ReverseWordsApp
    listKind: ReverseWordsAppList
    plural: reversewordsapps
    singular: reversewordsapp
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ReverseWordsApp is the Schema for the reversewordsapps API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ReverseWordsAppSpec defines the desired state of ReverseWordsApp
          properties:
            replicas:
              format: int32
              type: integer
          required:
          - replicas
          type: object
        status:
          description: ReverseWordsAppStatus defines the observed state of ReverseWordsApp
          properties:
            appPods:
              items:
                type: string
              type: array
          required:
          - appPods
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
